<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Shared\CRM.Shared.Infrastructure\CRM.Shared.Infrastructure.csproj" />
	  <ProjectReference Include="..\CRM.Billing.Application\CRM.Billing.Application.csproj" />
	  <ProjectReference Include="..\CRM.Billing.Infrastructure\CRM.Billing.Infrastructure.csproj" />
	</ItemGroup>

</Project>
