<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="MassTransit.RabbitMQ" />
		<PackageReference Include="AWSSDK.S3" />
		<PackageReference Include="Dapper" />
		<PackageReference Include="Scrutor" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="AspNetCore.HealthChecks.Aws.S3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CRM.Shared.Abstractions\CRM.Shared.Abstractions.csproj" />
	</ItemGroup>
</Project>
