// <auto-generated />
using System;
using CRM.Ordering.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Ordering.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    partial class OrderingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordering")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_attachments_order_id");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_attachments_uploaded_by");

                    b.ToTable("attachments", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateOnly?>("PlannedFinishDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_finish_date");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_orders_car_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_orders_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_orders_worker_id");

                    b.ToTable("orders", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.OrderGuarantee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date")
                        .HasColumnName("date_end");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date")
                        .HasColumnName("date_start");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("OrderPartId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_part_id");

                    b.Property<Guid?>("OrderWorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_work_id");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("terms");

                    b.HasKey("Id")
                        .HasName("pk_order_guarantees");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_guarantees_order_id");

                    b.HasIndex("OrderPartId")
                        .HasDatabaseName("ix_order_guarantees_order_part_id");

                    b.HasIndex("OrderWorkId")
                        .HasDatabaseName("ix_order_guarantees_order_work_id");

                    b.ToTable("order_guarantees", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.OrderPart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsProposed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proposed");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SoldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sold_price");

                    b.HasKey("Id")
                        .HasName("pk_order_parts");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_parts_order_id");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_order_parts_part_id");

                    b.ToTable("order_parts", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.OrderWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<decimal?>("FixedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fixed_price");

                    b.Property<decimal?>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("IsProposed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proposed");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("TimeSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("time_spent");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_cost");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_order_works");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_order_works_job_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_works_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_order_works_status");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_order_works_worker_id");

                    b.ToTable("order_works", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.WorkProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_work_proposals");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_work_proposals_job_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_work_proposals_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_work_proposals_status");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_work_proposals_worker_id");

                    b.ToTable("work_proposals", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.ServiceCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("StandardTime")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("standard_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service_catalog_items");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_service_catalog_items_category");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_service_catalog_items_title");

                    b.ToTable("service_catalog_items", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.VehicleInspections.VehicleInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CleanlinessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("cleanliness_level");

                    b.Property<bool>("ClientSign")
                        .HasColumnType("boolean")
                        .HasColumnName("client_sign");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DashboardWarnings")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("dashboard_warnings");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ExternalDefects")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("external_defects");

                    b.Property<int>("FuelLevel")
                        .HasColumnType("integer")
                        .HasColumnName("fuel_level");

                    b.Property<bool>("HasServiceBook")
                        .HasColumnType("boolean")
                        .HasColumnName("has_service_book");

                    b.Property<bool>("HasWheelNutKey")
                        .HasColumnType("boolean")
                        .HasColumnName("has_wheel_nut_key");

                    b.Property<string>("InternalDefects")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("internal_defects");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PersonalBelongings")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("personal_belongings");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.Property<bool>("WorkerSign")
                        .HasColumnType("boolean")
                        .HasColumnName("worker_sign");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_inspections");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_vehicle_inspections_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_vehicle_inspections_status");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_vehicle_inspections_worker_id");

                    b.ToTable("vehicle_inspections", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.VehicleInspections.VehicleInspectionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_inspection_images");

                    b.HasIndex("InspectionId")
                        .HasDatabaseName("ix_vehicle_inspection_images_inspection_id");

                    b.ToTable("vehicle_inspection_images", "ordering");
                });

            modelBuilder.Entity("CRM.Shared.Infrastructure.Data.InboxMessages.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "ordering");
                });

            modelBuilder.Entity("CRM.Shared.Infrastructure.Data.OutboxMessages.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_occurred_on_utc");

                    b.ToTable("outbox_messages", "ordering");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.OrderGuarantee", b =>
                {
                    b.HasOne("CRM.Ordering.Domain.Entities.Orders.Order", null)
                        .WithMany("Guarantees")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_guarantees_orders_order_id");

                    b.HasOne("CRM.Ordering.Domain.Entities.Orders.OrderPart", null)
                        .WithMany()
                        .HasForeignKey("OrderPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_guarantees_order_parts_order_part_id");

                    b.HasOne("CRM.Ordering.Domain.Entities.Orders.OrderWork", null)
                        .WithMany()
                        .HasForeignKey("OrderWorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_guarantees_order_works_order_work_id");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.OrderPart", b =>
                {
                    b.HasOne("CRM.Ordering.Domain.Entities.Orders.Order", null)
                        .WithMany("Parts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_parts_orders_order_id");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.OrderWork", b =>
                {
                    b.HasOne("CRM.Ordering.Domain.Entities.Orders.Order", null)
                        .WithMany("Works")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_works_orders_order_id");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.VehicleInspections.VehicleInspectionImage", b =>
                {
                    b.HasOne("CRM.Ordering.Domain.Entities.VehicleInspections.VehicleInspection", null)
                        .WithMany("Images")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_inspection_images_vehicle_inspections_inspection_id");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("Guarantees");

                    b.Navigation("Parts");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("CRM.Ordering.Domain.Entities.VehicleInspections.VehicleInspection", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
