<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Modules\Billing\CRM.Billing.Domain\CRM.Billing.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Customers\CRM.Customers.Domain\CRM.Customers.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\HR\CRM.HR.Domain\CRM.HR.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\IAM\CRM.IAM.Domain\CRM.IAM.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Inventory\CRM.Inventory.Domain\CRM.Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Notifications\CRM.Notifications.Domain\CRM.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Ordering\CRM.Ordering.Domain\CRM.Ordering.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Shared\CRM.Shared.Abstractions\CRM.Shared.Abstractions.csproj" />
  </ItemGroup>

</Project>
