<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Modules\Billing\CRM.Billing.Infrastructure\CRM.Billing.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\Shared\CRM.Shared.Abstractions\CRM.Shared.Abstractions.csproj" />
	  <ProjectReference Include="..\..\..\Shared\CRM.Shared.Infrastructure\CRM.Shared.Infrastructure.csproj" />
	</ItemGroup>

</Project>
