<Project Sdk="Microsoft.NET.Sdk.Web">


	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Modules\Billing\CRM.Billing.Api\CRM.Billing.Api.csproj" />
	  <ProjectReference Include="..\..\..\Modules\Customers\CRM.Customers.Infrastructure\CRM.Customers.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\Modules\HR\CRM.HR.Infrastructure\CRM.HR.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\Modules\IAM\CRM.IAM.Infrastructure\CRM.IAM.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\Modules\Inventory\CRM.Inventory.Infrastructure\CRM.Inventory.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\Modules\Notifications\CRM.Notifications.Infrastructure\CRM.Notifications.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\Modules\Ordering\CRM.Ordering.Infrastructure\CRM.Ordering.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\Shared\CRM.Shared.Abstractions\CRM.Shared.Abstractions.csproj" />
	  <ProjectReference Include="..\..\..\Shared\CRM.Shared.Infrastructure\CRM.Shared.Infrastructure.csproj" />
	</ItemGroup>

</Project>
