<Project Sdk="Microsoft.NET.Sdk">
	
	<ItemGroup>
		<PackageReference Include="MassTransit.RabbitMQ" />
	</ItemGroup>
	
	<ItemGroup>
		<Folder Include="Features\Bills\Queries\" />
		<Folder Include="Features\Expenses\Queries\" />
		<Folder Include="Features\PriceLists\Queries\" />
		<Folder Include="Features\Taxes\Queries\" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\..\Shared\CRM.Shared.Abstractions\CRM.Shared.Abstractions.csproj" />
		<ProjectReference Include="..\CRM.Billing.Domain\CRM.Billing.Domain.csproj" />
	</ItemGroup>
	
</Project>
