// <auto-generated />
using System;
using CRMSystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRMSystem.DataAccess.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20251209195621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AbsenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_absences");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_absences_worker_id");

                    b.ToTable("absences", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("ClientSign")
                        .HasColumnType("boolean")
                        .HasColumnName("client_sign");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("ExternalDefects")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("external_defects");

                    b.Property<int>("FuelLevel")
                        .HasColumnType("integer")
                        .HasColumnName("fuel_level");

                    b.Property<string>("InternalDefects")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("internal_defects");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.Property<bool?>("WorkerSign")
                        .HasColumnType("boolean")
                        .HasColumnName("worker_sign");

                    b.HasKey("Id")
                        .HasName("pk_acceptances");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_acceptances_order_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_acceptances_worker_id");

                    b.ToTable("acceptances", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceImgEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AcceptanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("acceptance_id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_path");

                    b.HasKey("Id")
                        .HasName("pk_acceptence_imgs");

                    b.HasIndex("AcceptanceId")
                        .HasDatabaseName("ix_acceptence_imgs_acceptance_id");

                    b.ToTable("acceptence_imgs", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_attachments_order_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_attachments_worker_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentImgEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AttachmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("attachment_id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_path");

                    b.HasKey("Id")
                        .HasName("pk_attachment_imgs");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_attachment_imgs_attachment_id");

                    b.ToTable("attachment_imgs", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("ActualBillDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_bill_date");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_bills_order_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_bills_status_id");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_bill_statuses");

                    b.ToTable("bill_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Оплачен"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Не оплачен"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Частично оплачен"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("brand");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("model");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<string>("StateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("state_number");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("VinNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin_number");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_manufacture");

                    b.HasKey("Id")
                        .HasName("pk_cars");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_cars_owner_id");

                    b.HasIndex("StateNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cars_state_number");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_cars_status_id");

                    b.HasIndex("VinNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cars_vin_number");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_car_statuses");

                    b.ToTable("car_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Не в работе"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ClientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("surname");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_phone_number");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_user_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ExpenseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expense_type");

                    b.Property<long?>("PartSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_set_id");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("sum");

                    b.Property<int?>("TaxId")
                        .HasColumnType("integer")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("PartSetId")
                        .HasDatabaseName("ix_expenses_part_set_id");

                    b.HasIndex("TaxId")
                        .HasDatabaseName("ix_expenses_tax_id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.GuaranteeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date")
                        .HasColumnName("date_end");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date")
                        .HasColumnName("date_start");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("terms");

                    b.HasKey("Id")
                        .HasName("pk_guarantees");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_guarantees_order_id");

                    b.ToTable("guarantees", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CarId")
                        .HasColumnType("bigint")
                        .HasColumnName("car_id");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("message");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("send_at");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_notifications_car_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_notifications_client_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_notifications_status_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_notification_statuses");

                    b.ToTable("notification_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Отправлено"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Прочитано"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CarId")
                        .HasColumnType("bigint")
                        .HasColumnName("car_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("priority");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_work_orders_car_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_work_orders_status_id");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_order_statuses");

                    b.ToTable("order_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В ожидании"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Принят"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Диагнстика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Закрыт"
                        },
                        new
                        {
                            Id = 5,
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Завершен"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_part_categories");

                    b.ToTable("part_categories", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Applicability")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("applicability");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("InternalArticle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("internal_article");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ManufacturerArticle")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manufacturer_article");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("OEMArticle")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("oem_article");

                    b.HasKey("Id")
                        .HasName("pk_parts");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_parts_category_id");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartSetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<long>("ProposalId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposal_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SoldPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("sold_price");

                    b.HasKey("Id")
                        .HasName("pk_part_sets");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_part_sets_order_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_part_sets_position_id");

                    b.HasIndex("ProposalId")
                        .IsUnique()
                        .HasDatabaseName("ix_part_sets_proposal_id");

                    b.ToTable("part_sets", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PaymentNoteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<long>("BillId")
                        .HasColumnType("bigint")
                        .HasColumnName("bill_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.HasKey("Id")
                        .HasName("pk_payment_journal");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_payment_journal_bill_id");

                    b.ToTable("payment_journal", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PositionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CellId")
                        .HasColumnType("integer")
                        .HasColumnName("cell_id");

                    b.Property<long>("PartId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("purchase_price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("selling_price");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("CellId")
                        .HasDatabaseName("ix_positions_cell_id");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_positions_part_id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Менеджер"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Клиент"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Работник"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_schedules_shift_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_schedules_worker_id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ShiftEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_at");

                    b.HasKey("Id")
                        .HasName("pk_shifts");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SkillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer")
                        .HasColumnName("specialization_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("SpecializationId")
                        .HasDatabaseName("ix_skills_specialization_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_skills_worker_id");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SpecializationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specializations");

                    b.ToTable("specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "автомеханик"
                        },
                        new
                        {
                            Id = 2,
                            Name = "моторист"
                        },
                        new
                        {
                            Id = 3,
                            Name = "специалист по коробкам передач"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ходовик"
                        },
                        new
                        {
                            Id = 5,
                            Name = "специалист по тормозным системам"
                        },
                        new
                        {
                            Id = 6,
                            Name = "автоэлектрик"
                        },
                        new
                        {
                            Id = 7,
                            Name = "диагност"
                        },
                        new
                        {
                            Id = 8,
                            Name = "кузовщик"
                        },
                        new
                        {
                            Id = 9,
                            Name = "маляр"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.StorageCellEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("rack");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("shelf");

                    b.HasKey("Id")
                        .HasName("pk_storage_cells");

                    b.ToTable("storage_cells", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contacts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_supplies");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplies_supplier_id");

                    b.ToTable("supplies", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplySetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("purchase_price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("quantity");

                    b.Property<long>("SupplyId")
                        .HasColumnType("bigint")
                        .HasColumnName("supply_id");

                    b.HasKey("Id")
                        .HasName("pk_supply_sets");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_supply_sets_position_id");

                    b.HasIndex("SupplyId")
                        .HasDatabaseName("ix_supply_sets_supply_id");

                    b.ToTable("supply_sets", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.TaxEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(2, 2)")
                        .HasColumnName("rate");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_taxes");

                    b.ToTable("taxes", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_users_login");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<decimal>("StandardTime")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("standard_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_works_catalog");

                    b.ToTable("works_catalog", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkInOrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<decimal>("TimeSpent")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("time_spent");

                    b.Property<long?>("WorkProposalId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_proposal_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_works_in_order");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_works_in_order_job_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_works_in_order_order_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_works_in_order_status_id");

                    b.HasIndex("WorkProposalId")
                        .HasDatabaseName("ix_works_in_order_work_proposal_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_works_in_order_worker_id");

                    b.ToTable("works_in_order", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkInOrderStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_work_in_order_statuses");

                    b.ToTable("work_in_order_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В ожидании"
                        },
                        new
                        {
                            Id = 3,
                            Name = "завершен"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_additional_work_proposals");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_additional_work_proposals_job_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_additional_work_proposals_order_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_additional_work_proposals_status_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_additional_work_proposals_worker_id");

                    b.ToTable("additional_work_proposals", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_work_proposal_statuses");

                    b.ToTable("work_proposal_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В ожидании"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Принято"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Отклонено"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal (8, 2)")
                        .HasColumnName("hourly_rate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("surname");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_workers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_workers_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workers_phone_number");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_workers_user_id");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AbsenceEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Absences")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_absences_workers_worker_id");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("Acceptances")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_acceptances_orders_order_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Acceptances")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_acceptances_workers_worker_id");

                    b.Navigation("Order");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceImgEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.AcceptanceEntity", "Acceptance")
                        .WithMany("Imgs")
                        .HasForeignKey("AcceptanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acceptence_imgs_acceptances_acceptance_id");

                    b.Navigation("Acceptance");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("Attachments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_orders_order_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Attachments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_workers_worker_id");

                    b.Navigation("Order");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentImgEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.AttachmentEntity", "Attachment")
                        .WithMany("Imgs")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachment_imgs_attachments_attachment_id");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("Bills")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_orders_order_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.BillStatusEntity", "Status")
                        .WithMany("Bills")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_bills_statuses_status_id");

                    b.Navigation("Order");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cars_clients_owner_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.CarStatusEntity", "Status")
                        .WithMany("Cars")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cars_car_statuses_status_id");

                    b.Navigation("Client");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ClientEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.UserEntity", "User")
                        .WithOne("Client")
                        .HasForeignKey("CRMSystem.DataAccess.Entites.ClientEntity", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ExpenseEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.PartSetEntity", "PartSet")
                        .WithMany("Expenses")
                        .HasForeignKey("PartSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expenses_part_sets_part_set_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.TaxEntity", "Tax")
                        .WithMany("Expenses")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expenses_taxes_tax_id");

                    b.Navigation("PartSet");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.GuaranteeEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("Guarantees")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guarantees_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Notifications")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_cars_car_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Notifications")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_clients_client_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.NotificationStatusEntity", "Status")
                        .WithMany("Notifications")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_notifications_statuses_status_id");

                    b.Navigation("Car");

                    b.Navigation("Client");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_cars_car_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.OrderStatusEntity", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_order_statuses_status_id");

                    b.Navigation("Car");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.PartCategoryEntity", "PartCategory")
                        .WithMany("Parts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parts_part_categories_category_id");

                    b.Navigation("PartCategory");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartSetEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("PartSets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_part_sets_orders_order_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.PositionEntity", "Position")
                        .WithMany("PartSets")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_part_sets_positions_position_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkProposalEntity", "WorkProposal")
                        .WithOne("PartSet")
                        .HasForeignKey("CRMSystem.DataAccess.Entites.PartSetEntity", "ProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_part_sets_work_proposals_proposal_id");

                    b.Navigation("Order");

                    b.Navigation("Position");

                    b.Navigation("WorkProposal");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PaymentNoteEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.BillEntity", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_journal_bills_bill_id");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PositionEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.StorageCellEntity", "StorageCell")
                        .WithMany("Positions")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_storage_cells_cell_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.PartEntity", "Part")
                        .WithMany("Positions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_parts_part_id");

                    b.Navigation("Part");

                    b.Navigation("StorageCell");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ScheduleEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.ShiftEntity", "Shift")
                        .WithMany("Schedules")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_shifts_shift_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Schedules")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_workers_worker_id");

                    b.Navigation("Shift");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SkillEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.SpecializationEntity", "Specialization")
                        .WithMany("Skills")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skills_specializations_specialization_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Skills")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skills_workers_worker_id");

                    b.Navigation("Specialization");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplyEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.SupplierEntity", "Supplier")
                        .WithMany("Supplies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supplies_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplySetEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.PositionEntity", "Position")
                        .WithMany("SupplySets")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supply_sets_positions_position_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.SupplyEntity", "Supply")
                        .WithMany("SupplySets")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supply_sets_supplies_supply_id");

                    b.Navigation("Position");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.UserEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkInOrderEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.WorkEntity", "Work")
                        .WithMany("WorksInOrder")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_works_in_order_works_catalog_job_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("WorksInOrder")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_works_in_order_orders_order_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkInOrderStatusEntity", "WorkInOrderStatus")
                        .WithMany("Works")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_works_in_order_work_in_order_statuses_status_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkProposalEntity", "WorkProposal")
                        .WithMany()
                        .HasForeignKey("WorkProposalId")
                        .HasConstraintName("fk_works_in_order_work_proposals_work_proposal_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("WorksInOrder")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_works_in_order_workers_worker_id");

                    b.Navigation("Order");

                    b.Navigation("Work");

                    b.Navigation("WorkInOrderStatus");

                    b.Navigation("WorkProposal");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.WorkEntity", "Work")
                        .WithMany("WorkProposals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_additional_work_proposals_works_catalog_job_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("WorkProposals")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_additional_work_proposals_work_orders_order_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkProposalStatusEntity", "Status")
                        .WithMany("Proposals")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_additional_work_proposals_work_proposal_statuses_status_id");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("WorkProposals")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_additional_work_proposals_workers_worker_id");

                    b.Navigation("Order");

                    b.Navigation("Status");

                    b.Navigation("Work");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkerEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.UserEntity", "User")
                        .WithOne("Worker")
                        .HasForeignKey("CRMSystem.DataAccess.Entites.WorkerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceEntity", b =>
                {
                    b.Navigation("Imgs");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentEntity", b =>
                {
                    b.Navigation("Imgs");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillStatusEntity", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarEntity", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarStatusEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ClientEntity", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationStatusEntity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderEntity", b =>
                {
                    b.Navigation("Acceptances");

                    b.Navigation("Attachments");

                    b.Navigation("Bills");

                    b.Navigation("Guarantees");

                    b.Navigation("PartSets");

                    b.Navigation("WorkProposals");

                    b.Navigation("WorksInOrder");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderStatusEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartCategoryEntity", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartEntity", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartSetEntity", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PositionEntity", b =>
                {
                    b.Navigation("PartSets");

                    b.Navigation("SupplySets");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ShiftEntity", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SpecializationEntity", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.StorageCellEntity", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplierEntity", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplyEntity", b =>
                {
                    b.Navigation("SupplySets");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.TaxEntity", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.UserEntity", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkEntity", b =>
                {
                    b.Navigation("WorkProposals");

                    b.Navigation("WorksInOrder");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkInOrderStatusEntity", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalEntity", b =>
                {
                    b.Navigation("PartSet");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalStatusEntity", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkerEntity", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Acceptances");

                    b.Navigation("Attachments");

                    b.Navigation("Schedules");

                    b.Navigation("Skills");

                    b.Navigation("WorkProposals");

                    b.Navigation("WorksInOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
