// <auto-generated />
using System;
using CRMSystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRMSystem.DataAccess.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20251218225603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AbsenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("WorkerId");

                    b.ToTable("absences", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AbsenceTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("absence_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Больничный"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Прогул"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Отпуск"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Отгул"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("ClientSign")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalDefects")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FuelLevel")
                        .HasColumnType("integer");

                    b.Property<string>("InternalDefects")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.Property<bool?>("WorkerSign")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("WorkerId");

                    b.ToTable("acceptances", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceImgEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AcceptanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptanceId");

                    b.ToTable("acceptance_imgs", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("WorkerId");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentImgEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AttachmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.ToTable("attachment_imgs", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("ActualBillDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("bill_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Оплачен"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Не оплачен"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Частично оплачен"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("VinNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StateNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("VinNumber")
                        .IsUnique();

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("car_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Не в работе"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ClientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ExpenseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("integer");

                    b.Property<long?>("PartSetId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TaxId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("PartSetId");

                    b.HasIndex("TaxId");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ExpenseTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("expense_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Запчасти и материалы"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Аренда и коммунальные услуги"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Оборудование и инструмент"
                        },
                        new
                        {
                            Id = 4,
                            Name = "IT и связь"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Маркетинг и реклама"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Документация и лицензии"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Логистика и транспорт"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Офисные и хозяйственные расходы"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Финансовые расходы"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.GuaranteeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("guarantees", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CarId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("notification_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Отправлено"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Прочитано"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("notification_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Работа с заказами"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Платежи и финансы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Запчасти и склад"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Планирование и обслуживание"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Системные уведомления"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Коммуникация с клиентами"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CarId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderPriorityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("order_priorities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Низкий"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Обычый"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Высокий"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("order_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В ожидании"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Принят"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Диагнстика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Закрыт"
                        },
                        new
                        {
                            Id = 5,
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Завершен"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("part_categories", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Applicability")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("InternalArticle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ManufacturerArticle")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OEMArticle")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartSetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProposalId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("SoldPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PositionId");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("part_sets", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PaymentMethodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("payment_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Картой"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Наличными"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ЕРИП"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PaymentNoteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("BillId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("MethodId");

                    b.ToTable("payment_journal", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PositionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CellId")
                        .HasColumnType("integer");

                    b.Property<long>("PartId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("PartId");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Менеджер"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Клиент"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Работник"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("WorkerId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ShiftEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<TimeOnly>("StartAt")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SkillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("WorkerId");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SpecializationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "автомеханик"
                        },
                        new
                        {
                            Id = 2,
                            Name = "моторист"
                        },
                        new
                        {
                            Id = 3,
                            Name = "специалист по коробкам передач"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ходовик"
                        },
                        new
                        {
                            Id = 5,
                            Name = "специалист по тормозным системам"
                        },
                        new
                        {
                            Id = 6,
                            Name = "автоэлектрик"
                        },
                        new
                        {
                            Id = 7,
                            Name = "диагност"
                        },
                        new
                        {
                            Id = 8,
                            Name = "кузовщик"
                        },
                        new
                        {
                            Id = 9,
                            Name = "маляр"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.StorageCellEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("storage_cells", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplies", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplySetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("SupplyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("SupplyId");

                    b.ToTable("supply_sets", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.TaxEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(2, 2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("taxes", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.TaxTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("tax_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Налог на прибыль"
                        },
                        new
                        {
                            Id = 2,
                            Name = "НДС"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Налог на недвижимость"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Земельный налог"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Социальные взносы"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Экологический налог"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Местные сборы"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("StandardTime")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("works_catalog", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkInOrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TimeSpent")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<long?>("WorkProposalId")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkProposalId");

                    b.HasIndex("WorkerId");

                    b.ToTable("works_in_order", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkInOrderStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("work_in_order_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В ожидании"
                        },
                        new
                        {
                            Id = 3,
                            Name = "завершен"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkerId");

                    b.ToTable("additional_work_proposals", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("work_proposal_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В ожидании"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Принято"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Отклонено"
                        });
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal (8, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AbsenceEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.AbsenceTypeEntity", "AbsenceType")
                        .WithMany("Absences")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Absences")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbsenceType");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("Acceptances")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Acceptances")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceImgEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.AcceptanceEntity", "Acceptance")
                        .WithMany("Imgs")
                        .HasForeignKey("AcceptanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acceptance");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("Attachments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Attachments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentImgEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.AttachmentEntity", "Attachment")
                        .WithMany("Imgs")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("Bills")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.BillStatusEntity", "Status")
                        .WithMany("Bills")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.CarStatusEntity", "Status")
                        .WithMany("Cars")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ClientEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.UserEntity", "User")
                        .WithOne("Client")
                        .HasForeignKey("CRMSystem.DataAccess.Entites.ClientEntity", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ExpenseEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.ExpenseTypeEntity", "ExpenseType")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.PartSetEntity", "PartSet")
                        .WithMany("Expenses")
                        .HasForeignKey("PartSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMSystem.DataAccess.Entites.TaxEntity", "Tax")
                        .WithMany("Expenses")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExpenseType");

                    b.Navigation("PartSet");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.GuaranteeEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("Guarantees")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Notifications")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Notifications")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.NotificationStatusEntity", "Status")
                        .WithMany("Notifications")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.NotificationTypeEntity", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");

                    b.Navigation("NotificationType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.OrderPriorityEntity", "OrderPriority")
                        .WithMany("Orders")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.OrderStatusEntity", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("OrderPriority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.PartCategoryEntity", "PartCategory")
                        .WithMany("Parts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartCategory");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartSetEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("PartSets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRMSystem.DataAccess.Entites.PositionEntity", "Position")
                        .WithMany("PartSets")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkProposalEntity", "WorkProposal")
                        .WithOne("PartSet")
                        .HasForeignKey("CRMSystem.DataAccess.Entites.PartSetEntity", "ProposalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Position");

                    b.Navigation("WorkProposal");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PaymentNoteEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.BillEntity", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.PaymentMethodEntity", "Method")
                        .WithMany("PaymentNotes")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PositionEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.StorageCellEntity", "StorageCell")
                        .WithMany("Positions")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.PartEntity", "Part")
                        .WithMany("Positions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("StorageCell");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ScheduleEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.ShiftEntity", "Shift")
                        .WithMany("Schedules")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Schedules")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SkillEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.SpecializationEntity", "Specialization")
                        .WithMany("Skills")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("Skills")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplyEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.SupplierEntity", "Supplier")
                        .WithMany("Supplies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplySetEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.PositionEntity", "Position")
                        .WithMany("SupplySets")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.SupplyEntity", "Supply")
                        .WithMany("SupplySets")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.TaxEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.TaxTypeEntity", "TaxType")
                        .WithMany("Taxes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaxType");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.UserEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkInOrderEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.WorkEntity", "Work")
                        .WithMany("WorksInOrder")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("WorksInOrder")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkInOrderStatusEntity", "WorkInOrderStatus")
                        .WithMany("Works")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkProposalEntity", "WorkProposal")
                        .WithMany()
                        .HasForeignKey("WorkProposalId");

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("WorksInOrder")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Work");

                    b.Navigation("WorkInOrderStatus");

                    b.Navigation("WorkProposal");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.WorkEntity", "Work")
                        .WithMany("WorkProposals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.OrderEntity", "Order")
                        .WithMany("WorkProposals")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkProposalStatusEntity", "Status")
                        .WithMany("Proposals")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMSystem.DataAccess.Entites.WorkerEntity", "Worker")
                        .WithMany("WorkProposals")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Status");

                    b.Navigation("Work");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkerEntity", b =>
                {
                    b.HasOne("CRMSystem.DataAccess.Entites.UserEntity", "User")
                        .WithOne("Worker")
                        .HasForeignKey("CRMSystem.DataAccess.Entites.WorkerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AbsenceTypeEntity", b =>
                {
                    b.Navigation("Absences");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AcceptanceEntity", b =>
                {
                    b.Navigation("Imgs");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.AttachmentEntity", b =>
                {
                    b.Navigation("Imgs");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.BillStatusEntity", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarEntity", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.CarStatusEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ClientEntity", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ExpenseTypeEntity", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationStatusEntity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.NotificationTypeEntity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderEntity", b =>
                {
                    b.Navigation("Acceptances");

                    b.Navigation("Attachments");

                    b.Navigation("Bills");

                    b.Navigation("Guarantees");

                    b.Navigation("PartSets");

                    b.Navigation("WorkProposals");

                    b.Navigation("WorksInOrder");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderPriorityEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.OrderStatusEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartCategoryEntity", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartEntity", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PartSetEntity", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PaymentMethodEntity", b =>
                {
                    b.Navigation("PaymentNotes");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.PositionEntity", b =>
                {
                    b.Navigation("PartSets");

                    b.Navigation("SupplySets");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.ShiftEntity", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SpecializationEntity", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.StorageCellEntity", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplierEntity", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.SupplyEntity", b =>
                {
                    b.Navigation("SupplySets");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.TaxEntity", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.TaxTypeEntity", b =>
                {
                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.UserEntity", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkEntity", b =>
                {
                    b.Navigation("WorkProposals");

                    b.Navigation("WorksInOrder");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkInOrderStatusEntity", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalEntity", b =>
                {
                    b.Navigation("PartSet");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkProposalStatusEntity", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("CRMSystem.DataAccess.Entites.WorkerEntity", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Acceptances");

                    b.Navigation("Attachments");

                    b.Navigation("Schedules");

                    b.Navigation("Skills");

                    b.Navigation("WorkProposals");

                    b.Navigation("WorksInOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
