<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Ordering\CRM.Ordering.Domain\CRM.Ordering.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\Shared\CRM.Shared.Abstractions\CRM.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\CRM.TestHelpers\CRM.TestHelpers.csproj" />
  </ItemGroup>
</Project>
